FROM docker.io/alpine:latest
RUN apk update && apk add nodejs

EXPOSE 3000

VOLUME /root/.config/music-app
VOLUME /root/music
VOLUME /root/www

WORKDIR /root/www
ENV MUSIC_SETTINGS_DIR "/root/.config/music-app"
ENV MUSIC_DIR "/root/music"
ENTRYPOINT node index.mjs
