FROM docker.io/alpine:latest
EXPOSE 3000
VOLUME /root/www
VOLUME /root/music
RUN apk update && apk add nodejs
WORKDIR /root/www
ENV GMAIL_USER "castle.rpi"
ENV GMAIL_PASS "kczacodluljrtdqh"
ENTRYPOINT node music-app/back-end/index.mjs
